language: node_js

matrix:
  include:
  - node_js: '12'
cache:
  directories: [node_modules]
install:
  yarn
before_script:
  - bash -x psql -c 'create database testdb;' -U postgres
  - echo $!
script:
  - yarn runQuery
  - yarn test
after_script:
  - --exit-code $TRAVIS_TEST_RESUL
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
before_install:
  - sudo cp /etc/postgresql/{9.6,10}/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
